import { defineConfig, type UserConfig } from 'tsdown'

const config: UserConfig = defineConfig({
  entry: ['src/index.ts', 'src/cli.ts'],
  format: 'esm',
  target: 'node20',
  minify: true,
  clean: true,
  // Keep declaration files and declaration maps generated by tsc.
  dts: false,
  outExtensions: () => ({ js: '.js' }),
})

export default config
